/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhansu;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.Buffer;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quyto
 */
public class QuanLyNhanSu extends javax.swing.JFrame {

    
    DefaultTableModel dtm1;
    DefaultTableModel dtm2;
    DefaultTableModel dtm3;
    
    
    ArrayList<BangQuanLy> listQuanLy= new ArrayList<>();
    
    public QuanLyNhanSu() throws FileNotFoundException {
        initComponents();
        showNV();
        showP();
        showQuanLy();
        comboboxData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangNV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oTenNV = new javax.swing.JTextField();
        oDiaChi = new javax.swing.JTextField();
        oSoDienThoai = new javax.swing.JTextField();
        oBacLuong = new javax.swing.JTextField();
        themNV = new javax.swing.JButton();
        oLoiNV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        oTenP = new javax.swing.JTextField();
        oMoTa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oHeSo = new javax.swing.JTextField();
        themP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangP = new javax.swing.JTable();
        oLoiP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bangQL = new javax.swing.JTable();
        themQuanLy = new javax.swing.JButton();
        oSoNgayLV = new javax.swing.JTextField();
        cbbMaNV = new javax.swing.JComboBox<>();
        cbbMaP = new javax.swing.JComboBox<>();
        oLoiQL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên nhân viên");

        bangNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Địa chỉ", "Số điện thoại", "Bậc lương"
            }
        ));
        jScrollPane1.setViewportView(bangNV);

        jLabel2.setText("Địa chỉ");

        jLabel3.setText("Bậc lương (1-9)");

        jLabel4.setText("Số điện thoại ");

        themNV.setText("Thêm");
        themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(17, 17, 17)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oBacLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(themNV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(oLoiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(oDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(oSoDienThoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(oBacLuong)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(oLoiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(themNV))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Nhân viên", jPanel1);

        jLabel5.setText("Tên phong");

        jLabel6.setText("Mô tả");

        jLabel7.setText("Hệ số");

        themP.setText("Thêm");
        themP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themPActionPerformed(evt);
            }
        });

        bangP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng", "Mô tả", "Hệ số công viêc"
            }
        ));
        jScrollPane2.setViewportView(bangP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oLoiP, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(637, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(oMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oTenP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themP))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(oLoiP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(oTenP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(oMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addComponent(oHeSo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(themP))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)))
        );

        jTabbedPane1.addTab("Phòng ban", jPanel2);

        jLabel8.setText("Ma Nhan vien");

        jLabel9.setText("Phong Ban");

        jLabel10.setText("Số ngày LV");

        bangQL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Mã phòng", "Tên Phòng", "Số ngày làm"
            }
        ));
        jScrollPane3.setViewportView(bangQL);

        themQuanLy.setText("Thêm");
        themQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themQuanLyActionPerformed(evt);
            }
        });

        cbbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbMaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbbMaP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oSoNgayLV, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(cbbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(oLoiQL, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(625, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addComponent(themQuanLy)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(oSoNgayLV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(oLoiQL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(themQuanLy))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)))
        );

        jTabbedPane1.addTab("Quản lý", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNVActionPerformed
        if(evt.getSource()==themNV){
            try {
                oLoiNV.setText("");
                
                int ma=0, soDong=0;
                File file = new File("NV.TXT");
                if(!file.exists()){
                    file.createNewFile();
                }
                Scanner sc= new Scanner(file);
                if(!sc.hasNextLine()){
                    ma=1000;
                }else{
                    while(sc.hasNextLine()){
                        sc.nextLine();
                        soDong++;
                    }
                    ma=soDong/5 +1000;
                }
                sc.close();
                
                if(oTenNV.getText()==null || oTenNV.getText().trim().isEmpty()){
                    oLoiNV.setText("Chua nhap o ten nv");
                    throw new Exception();
                }
                if(oDiaChi.getText()==null || oDiaChi.getText().trim().isEmpty()){
                    oLoiNV.setText("Chua nhap o dia chi");
                    throw new Exception();
                }
                if(oSoDienThoai.getText()==null || oSoDienThoai.getText().trim().isEmpty()){
                    oLoiNV.setText("Chua nhap o so dien thoai");
                    throw new Exception();
                }
                if(oBacLuong.getText()==null || oBacLuong.getText().trim().isEmpty()){
                    oLoiNV.setText("Chua nhap o bac luong");
                    throw new Exception();
                }
                
                FileWriter fw= new FileWriter(file.getAbsoluteFile(),true);
                BufferedWriter bw= new BufferedWriter(fw);
                
                bw.write(ma+"\n");
                bw.write(oTenNV.getText()+"\n");
                bw.write(oDiaChi.getText()+"\n");
                bw.write(Integer.parseInt(oSoDienThoai.getText())+"\n");
                bw.write(Integer.parseInt(oBacLuong.getText())+"\n");
                
                bw.close();
                fw.close();
                showNV();
                
            } catch(NumberFormatException e){
                oLoiNV.setText("Sai dinh dang");
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_themNVActionPerformed

    private void themPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themPActionPerformed
        if(evt.getSource()==themP){
            try {
                oLoiP.setText("");
                
                int ma=0, soDong=0;
                File file = new File("P.TXT");
                if(!file.exists()){
                    file.createNewFile();
                }
                Scanner sc= new Scanner(file);
                if(!sc.hasNextLine()){
                    ma=100;
                }else{
                    while(sc.hasNextLine()){
                        sc.nextLine();
                        soDong++;
                    }
                    ma=soDong/4 +100;
                }
                sc.close();
                
                if(oTenP.getText()==null || oTenP.getText().trim().isEmpty()){
                    oLoiP.setText("Chua nhap o ten P");
                    throw new Exception();
                }
                if(oMoTa.getText()==null || oMoTa.getText().trim().isEmpty()){
                    oLoiP.setText("Chua nhap o mo ta");
                    throw new Exception();
                }
                if(oHeSo.getText()==null || oHeSo.getText().trim().isEmpty()){
                    oLoiP.setText("Chua nhap o he so");
                    throw new Exception();
                }
                
                if(Integer.parseInt(oHeSo.getText())>20){
                    if(Integer.parseInt(oHeSo.getText())!=0){
                        oLoiP.setText("he so chi tu 1 den 20");
                        throw new Exception();
                    }
                }
                
                FileWriter fw= new FileWriter(file.getAbsoluteFile(),true);
                BufferedWriter bw= new BufferedWriter(fw);
                
                bw.write(ma+"\n");
                bw.write(oTenP.getText()+"\n");
                bw.write(oMoTa.getText()+"\n");
                bw.write(Integer.parseInt(oHeSo.getText())+"\n");
              
                
                bw.close();
                fw.close();
                showP();
                
            } catch(NumberFormatException e){
                oLoiP.setText("Sai dinh dang");
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_themPActionPerformed

    private void themQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themQuanLyActionPerformed
        if(evt.getSource()==themQuanLy){
            try {
                oLoiQL.setText("");
                
                
                if(oSoNgayLV.getText()==null || oSoNgayLV.getText().trim().isEmpty()){
                    oLoiQL.setText("Chua nhap so ngay Lv");
                    throw new Exception();
                }
                
                int maNV=0, maP=0, sl=0;
                maNV= Integer.parseInt(cbbMaNV.getSelectedItem().toString());
                maP= Integer.parseInt(cbbMaP.getSelectedItem().toString());
                sl= Integer.parseInt(oSoNgayLV.getText());
                
                int exist=0;
                
                BangQuanLy ql= new BangQuanLy();
                for(BangQuanLy s:listQuanLy){
                    if(s.getNv().getMaNV()==maNV && s.getP().getMaP()==maP){
                        s.setSoNgayLV(s.getSoNgayLV()+sl);
                        exist=1;
                        ghiQuanLy();
                        showQuanLy();
                        break;
                    }
                }
                
                if(exist==0){
                    for(NhanVien s:listNV()){
                        if(maNV== s.getMaNV()){
                            ql.setNv(s);
                            break;
                        }
                    }
                    for(PhongBan s:listP()){
                        if(maP== s.getMaP()){
                            ql.setP(s);
                            break;
                        }
                    }
                    ql.setSoNgayLV(sl);
                    listQuanLy.add(ql);


                    ghiQuanLy();
                    showQuanLy();   
                }
                
              
            } catch(NumberFormatException e){
                oLoiQL.setText("Sai dinh dang");
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_themQuanLyActionPerformed

   
    
    
    
    public ArrayList<NhanVien> listNV() throws FileNotFoundException{
        ArrayList<NhanVien> list= new ArrayList<>();
        File file= new File("NV.TXT");
        if(file.exists()){
            Scanner sc= new Scanner(file);
            while(sc.hasNextLine()){
                NhanVien a= new NhanVien();
                a.setMaNV(Integer.parseInt(sc.nextLine()));
                a.setTenNV(sc.nextLine());
                a.setDiaChi(sc.nextLine());
                a.setSoDienThoai(Integer.parseInt(sc.nextLine()));
                a.setBacLuoong(Integer.parseInt(sc.nextLine()));
                list.add(a);
            }
            sc.close();
        }
        return list;
    }
    
    public ArrayList<PhongBan> listP() throws FileNotFoundException{
        ArrayList<PhongBan> list= new ArrayList<>();
        File file= new File("P.TXT");
        if(file.exists()){
            Scanner sc= new Scanner(file);
            while(sc.hasNextLine()){
                PhongBan a= new PhongBan();
                a.setMaP(Integer.parseInt(sc.nextLine()));
                a.setTenP(sc.nextLine());
                a.setMoTa(sc.nextLine());
                a.setHeSo(Integer.parseInt(sc.nextLine()));
                list.add(a);
            }
            sc.close();
        }
        return list;
    }
    
    public void showNV() throws FileNotFoundException{
        dtm1= (DefaultTableModel) bangNV.getModel();
        dtm1.setRowCount(0);
        for(NhanVien s:listNV()){
          Vector v= new Vector();
          v.add(s.getMaNV());
          v.add(s.getTenNV());
          v.add(s.getDiaChi());
          v.add(s.getSoDienThoai());
          v.add(s.getBacLuoong());
          dtm1.addRow(v);
        }
    }
    public void showP() throws FileNotFoundException{
        dtm2= (DefaultTableModel) bangP.getModel();
        dtm2.setRowCount(0);
        for(PhongBan s:listP()){
          Vector v= new Vector();
          v.add(s.getMaP());
          v.add(s.getTenP());
          v.add(s.getMoTa());
          v.add(s.getHeSo());
          dtm2.addRow(v);
        }
    }
    
    
    public Vector listMaNV() throws FileNotFoundException{
        Vector v= new Vector();
        for(NhanVien s:listNV()){
            v.add(s.getMaNV());
        }
        return v;
    }
    public Vector listMaP() throws FileNotFoundException{
        Vector v= new Vector();
        for(PhongBan s:listP()){
            v.add(s.getMaP());
        }
        return v;
    }
    public void comboboxData() throws FileNotFoundException{
        DefaultComboBoxModel dcb1= new DefaultComboBoxModel(listMaNV());
        cbbMaNV.setModel(dcb1);
        
        DefaultComboBoxModel dcb2= new DefaultComboBoxModel(listMaP());
        cbbMaP.setModel(dcb2);
        
    }
    
    public void ghiQuanLy() throws IOException{
        File file= new File("QLNS.TXT");
        if(!file.exists()){
            file.createNewFile();
        }
        FileWriter fw= new FileWriter(file);
        BufferedWriter bw= new BufferedWriter(fw);
        
        for(BangQuanLy s:listQuanLy){
            bw.write(s.getNv().getMaNV()+"\n");
            bw.write(s.getP().getMaP()+"\n");
            bw.write(s.getSoNgayLV()+"\n");
        }
        bw.close();
        fw.close();
    }
    
    public void docQuanLy() throws FileNotFoundException{
        File file= new File("QLNS.TXT");
        listQuanLy.clear();
        if(file.exists()){
            Scanner sc= new Scanner(file);
            
            int maNV=0, maP=0, sl=0;
            while(sc.hasNextLine()){
                maNV= Integer.parseInt(sc.nextLine());
                maP= Integer.parseInt(sc.nextLine());
                sl= Integer.parseInt(sc.nextLine());
                BangQuanLy ql= new BangQuanLy();
                for(NhanVien s:listNV()){
                    if(maNV== s.getMaNV()){
                        ql.setNv(s);
                        break;
                    }
                }
                for(PhongBan s:listP()){
                    if(maP== s.getMaP()){
                        ql.setP(s);
                        break;
                    }
                }
               ql.setSoNgayLV(sl); 
               listQuanLy.add(ql);
            }
            sc.close();
       }
        
    }
    
    public void showQuanLy() throws FileNotFoundException{
        docQuanLy();
        dtm3 = (DefaultTableModel) bangQL.getModel();
        dtm3.setRowCount(0);
        for(BangQuanLy s:listQuanLy){
            Vector v= new Vector();
            v.add(s.getNv().getMaNV());
            v.add(s.getNv().getTenNV());
            v.add(s.getP().getMaP());
            v.add(s.getP().getTenP());
            v.add(s.getSoNgayLV());
            dtm3.addRow(v);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyNhanSu().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(QuanLyNhanSu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangNV;
    private javax.swing.JTable bangP;
    private javax.swing.JTable bangQL;
    private javax.swing.JComboBox<String> cbbMaNV;
    private javax.swing.JComboBox<String> cbbMaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField oBacLuong;
    private javax.swing.JTextField oDiaChi;
    private javax.swing.JTextField oHeSo;
    private javax.swing.JLabel oLoiNV;
    private javax.swing.JLabel oLoiP;
    private javax.swing.JLabel oLoiQL;
    private javax.swing.JTextField oMoTa;
    private javax.swing.JTextField oSoDienThoai;
    private javax.swing.JTextField oSoNgayLV;
    private javax.swing.JTextField oTenNV;
    private javax.swing.JTextField oTenP;
    private javax.swing.JButton themNV;
    private javax.swing.JButton themP;
    private javax.swing.JButton themQuanLy;
    // End of variables declaration//GEN-END:variables
}
